# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2

jobs:
  test:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            apt-get update
            apt-get install -y bats
            bats test/gconf.bats

workflows:
  version: 2
  test:
    jobs:
      - test
